wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1676733128.943934
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 1
      - 13
      - 16
      - 23
      4: 3.10.9
      5: 0.13.10
      8:
      - 5
alpha:
  desc: null
  value: 1.0
architecture:
  desc: null
  value: resnet50
batch_size:
  desc: null
  value: 64
beta:
  desc: null
  value: 0.35
cl_views:
  desc: null
  value: sim-sim
cos:
  desc: null
  value: true
epochs:
  desc: null
  value: 90
feat_dim:
  desc: null
  value: 1024
gpu:
  desc: null
  value: null
learning_rate:
  desc: null
  value: 0.1
momentum:
  desc: null
  value: 0.9
randaug:
  desc: null
  value: true
randaug_m:
  desc: null
  value: 10
randaug_n:
  desc: null
  value: 2
schedule:
  desc: null
  value:
  - 860
  - 880
seed:
  desc: null
  value: null
start_epoch:
  desc: null
  value: 0
temp:
  desc: null
  value: 0.07
use_norm:
  desc: null
  value: true
warmup_epochs:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.0005
workers:
  desc: null
  value: 8
